version: '3.8'

services:
  speedtest:
    build: .
    container_name: vxspeedtest-server
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      # 自定义 URL 路径（不包含前导斜杠）
      # 例如: speedtest, test123, abvcd5
      - CUSTOM_URL=speedtest
      
      # 下载测速文件大小（单位：MB）
      - DOWNLOAD_SIZE=100
      
      # POST 上传大小限制（单位：MB）
      - POST_SIZE_LIMIT=1000
    
    # 可选：限制容器资源使用
    # deploy:
    #   resources:
    #     limits:
    #       cpus: '2'
    #       memory: 2G

    # 健康检查
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
